### ISSUE TITLE
小白求教

### ISSUE THREAD

**Issue by alukaka** [daydayupsnail/react-practice-gallery#1]
xixi

**Comment by daydayupsnail** [comment]
不好意思，回复晚了。
网页是要在浏览器端，打开的。
你运行了服务器包，有没有看见提示，运行？
localhost:8000

在 2016-12-21 10:50:09，"alukaka" <notifications@github.com> 写道：


请问一下 怎么运行 我你怕吗start后只是打开了服务器包 并没有看到网页界面
